apiVersion: v1
kind: Service
metadata:
  name: echoserver-nodeport-local
  labels:
    app: echoserver
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: echoserver