apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 35.204.127.252
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend